# This works with any React JS project that is scaffolded using Vite JS
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

npm_install:
    stage: .pre
    script: npm install

vitest:
    stage: test
    script: npm run test

pages:
    stage: deploy
    script:
        - npm run build
        - mkdir -p public
        - cp -r dist/* public/
    artifacts:
        paths:
            - public
    only:
        - master
